Extra pages
savoirfairelinux/starlight pull request #11
Opened 2018-08-21 15:59 UTC by AnthonyLaye

In pull request:

1. Page to edit employee information
2. Page to add skills
3. Change folder hierarchy for template files
4. Page for individual skills

2018-08-22 22:22 UTC, peakwinter requested changes
Could you add a couple more tests to cover some of the things missing in `views.py`? https://coveralls.io/builds/18592348/source?filename=starlight/views.py Thanks! :)

2018-08-23 16:05 UTC, AnthonyLaye commented
Changed a lot of the tests, I realized they were all returning status code 200 because they were just rendering the page. Now they return a 302 and we verify that data is actually being processed and redirected to the appropriate page

2018-08-27 16:48 UTC, peakwinter requested changes

2018-08-27 16:48 UTC, peakwinter commented on starlight/templates/profile_views/edit_profile.html
> +          <input name="username" id="username" type="text"  value="{{ employee.username }}">
These fields should have placeholder text or labels so that we know what they are for

2021-12-17 20:20 UTC, closed without merging